version: "3.9"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_quiz/db.sqlite3:/db.sqlite3
    ports:
      - "8000:8000"
    depends_on:
      - redis
  celery:
    build: .
    command: celery -A core worker -B
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - backend
      - redis
  celery-beat:
    build: .
    command: celery -A django_quiz beat -l INFO -S django
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - backend
      - redis
      - celery