# Generated by Django 3.2.5 on 2021-07-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210716_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-title']},
        ),
    ]
