# Generated by Django 3.2.5 on 2021-07-16 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_test_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='question',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='quiz.question'),
        ),
    ]
