# Generated by Django 3.2.5 on 2021-07-20 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20210720_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrun',
            name='user',
        ),
    ]
