# Generated by Django 3.2.5 on 2021-07-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_testrun_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerquestion',
            name='question_content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='answerquestion',
            name='answer',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='answerquestion',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
