# Generated by Django 3.2.5 on 2021-07-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20210721_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerquestion',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
