# Generated by Django 3.2.5 on 2021-07-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20210721_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='number',
            field=models.IntegerField(),
        ),
    ]
