# Generated by Django 3.2.5 on 2021-08-01 10:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_alter_test_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 10, 27, 29, 669296)),
        ),
        migrations.CreateModel(
            name='TestrunStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_answer', models.IntegerField(default=0)),
                ('total_runs', models.IntegerField(default=0)),
                ('testrun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.testrun')),
            ],
            options={
                'ordering': ['total_runs'],
            },
        ),
    ]
