# Generated by Django 3.2.5 on 2021-08-01 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20210801_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 12, 44, 11, 508526)),
        ),
    ]
