# Generated by Django 3.2.5 on 2021-08-01 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_alter_test_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 12, 52, 56, 157183)),
        ),
    ]
