# Generated by Django 3.2.5 on 2021-08-06 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_alter_test_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrunstat',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 6, 16, 28, 23, 124457)),
        ),
    ]
