# Generated by Django 3.2.5 on 2021-08-07 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20210806_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrunstat',
            name='user',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 15, 0, 19, 550607)),
        ),
    ]
