# Generated by Django 3.2.5 on 2021-08-07 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20210807_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrunstat',
            name='user',
        ),
        migrations.AddField(
            model_name='testrun',
            name='user',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 15, 9, 41, 610518)),
        ),
    ]
