# Generated by Django 3.2.5 on 2021-08-11 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_auto_20210807_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='total_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 13, 51, 55, 870606)),
        ),
    ]
